name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Gemfile if missing
        run: |
          if [ ! -f "Gemfile" ]; then
            echo 'source "https://rubygems.org"' > Gemfile
            echo 'gem "jekyll", "~> 4.4"' >> Gemfile
            echo 'gem "github-pages", group: :jekyll_plugins' >> Gemfile
          fi

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build -d ./_site

      - name: Verify build
        run: ls -la _site

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      - uses: actions/deploy-pages@v3
        id: deployment